### ISSUE TITLE
chare:使用token宏替代部分regex宏in token.rs

### ISSUE THREAD

**Issue by czw0818** [EnabledFish/Nyah#1]
Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running unittests (~\Nyah\target\debug\deps\nyah_parser-e8852603ea3120e8.exe)

running 1 test
test token::test::test_lexer ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

**Comment by EnabledFish** [comment]
Thx.
